//
//  LoginInteractor.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 26/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func doSomething(request: Login.Something.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Login.Something.Request)
  {
    worker = LoginWorker()
    worker?.doSomeWork()
    
    let response = Login.Something.Response()
    presenter?.presentSomething(response: response)
  }
    func saveUserLoginSwitch (){
        if (saveSwitch){
            
        }
    }
    
    func permformLogin() {
        worker?.loginRequest(url: , userLogin: <#T##String#>, userPassword: <#T##String#>, completionHandler: <#T##(Result<User, Error>) -> Void#>) { result in
            switch result {
            case .success(let user):
                // criar usuário
                // passar dados para a presenter
                // chamar o router para passar dados para a tela de extrato
                return
            case .failure(let error):
            
                return
            }
            
        }
    }
    
    func checkCPF() {
        worker.checkCPF()
        // retornar um verdadeiro ou false e devolver informações à presenter
        if (false) {
            
        }
    }
    
    func checkLogin() {
        worker.checkLogin()
        // retornar um verdadeiro ou false e devolver informações à presenter
        if (false) {
            
        }
    }
    
    func checkKeyChain() {
        worker.checkKeyChain()
        // retornar um verdadeiro ou false e devolver informações à presenter
        if (false) {
            
        }
    }
    
}
