//
//  LoginWorker.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 26/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import KeychainSwift

protocol LoginWorkerProtocol{
    func loginRequest(url: String, userLogin: String, userPassword: String, completionHandler: @escaping (Result<User, Error>) -> Void)
}


class LoginWorker: LoginWorkerProtocol {
    
    var request = ServiceRequest()
    let keyChain = KeyChainModel()
    
    func doSomeWork()
    {
    }
    
    func loginRequest(url: String, userLogin: String, userPassword: String, completionHandler: @escaping (Result<User, Error>) -> Void) {
        <#code#>
    }
    
    func saveUserKeyChain() {
        keyChain.storeData(data: "true", key: "boolean")
    }
    
    func dontSaveUserKeyChain() {
        keyChain.storeData(data: "false", key: "boolean")
    }
        
    
    
}
