//
//  LoginModels.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 26/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        let userLogin: String
        let userPassword: String
        let loginURL = "https://api.mobile.test.solutis.xyz/extrato"
    }
    struct Response
    {
        let nome: String
        let cpf: String
        let saldo: Double
        let token: String
    }
    struct ViewModel
    {
        
    }
  }
}
